# Generated by Django 3.2.25 on 2024-12-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='user_pk',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='albumId',
            new_name='album_pk',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='user',
            new_name='user_pk',
        ),
    ]
