# Generated by Django 3.2.25 on 2024-12-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20241212_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postId',
            new_name='post_pk',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_pk',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_pk',
        ),
    ]
