# Generated by Django 3.2.25 on 2024-12-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20241212_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='user_pk',
        ),
    ]
