# Generated by Django 3.2.25 on 2025-01-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user_pk',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='album_pk',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='user_pk',
            new_name='user',
        ),
    ]
