# Generated by Django 3.2.25 on 2025-01-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20250103_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnailUrl',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
